export const events = [
  {
    id: "1",
    title: "Kendrick Lamar - Grand National Tour",
    date: "2026-05-01",
    location: "New York City, NY",
    price: 120,

    fees: {
      service: 10,
      tax: 5,
    },

    deals: [
      "10% student discount",
      "Buy 2 get 1 free",
    ],

    budget: [
      { type: "Standard", price: 80 },
      { type: "VIP", price: 200 },
    ],

    notify: true,
  },
{
  id: "2",
  title: "Shakira - Las Mujeres Ya No Lloran World Tour",
  date: "2026-06-10",
  location: "San Jose, CA",
  price: 150,
  fees: { service: 12, tax: 8 },
  deals: ["Free drink with ticket"],
  budget: [
    { type: "Standard", price: 150 },
    { type: "VIP", price: 250 },
  ],
  notify: true,
},
{
  id: "3",
  title: "Chappel Roan - Midwest Princess Tour",
  date: "2026-07-15",
  location: "Los Angeles, CA",
  price: 300,
  fees: { service: 20, tax: 15 },
  deals: ["Early access tickets"],
  budget: [
    { type: "Standard", price: 300 },
    { type: "VIP", price: 500 },
  ],
  notify: true,
},
{
  id: "4",
  title: "CA7RIEL & Paco Amoroso - Free Spirits World Tour",
  date: "2026-08-05",
  location: "New York City, NY",
  price: 90,
  fees: { service: 8, tax: 4 },
  deals: ["Group discount"],
  budget: [
    { type: "Standard", price: 90 },
    { type: "VIP", price: 140 },
  ],
  notify: false,
},
{
  id: "5",
  title: "Rosalia - LUX World Tour",
  date: "2026-09-12",
  location: "New York City, NY",
  price: 478,
  fees: { service: 15, tax: 10 },
  deals: ["Merch bundle"],
  budget: [
    { type: "Standard", price: 180 },
    { type: "VIP", price: 300 },
  ],
  notify: true,
},
{
  id: "6",
  title: "Ralphie Choo Live",
  date: "2026-04-20",
  location: "Miami, FL",
  price: 70,
  fees: { service: 5, tax: 3 },
  deals: ["Student discount"],
  budget: [
    { type: "Standard", price: 70 },
    { type: "VIP", price: 110 },
  ],
  notify: false,
},
{
  id: "7",
  title: "Fred Again.. Concert",
  date: "2026-10-01",
  location: "Newark, NJ",
  price: 200,
  fees: { service: 18, tax: 12 },
  deals: ["VIP backstage pass"],
  budget: [
    { type: "Standard", price: 200 },
    { type: "VIP", price: 350 },
  ],
  notify: true,
},
{
  id: "8",
  title: "Bjork Experience",
  date: "2026-11-11",
  location: "Trenton, NJ",
  price: 220,
  fees: { service: 20, tax: 10 },
  deals: ["Exclusive visuals"],
  budget: [
    { type: "Standard", price: 220 },
    { type: "VIP", price: 400 },
  ],
  notify: true,
},
{
  id: "9",
  title: "Sabrina Carpenter - Man's Best Friend Tour",
  date: "2026-06-22",
  location: "Newark, NJ",
  price: 345,
  fees: { service: 6, tax: 4 },
  deals: ["Free merch"],
  budget: [
    { type: "Standard", price: 80 },
    { type: "VIP", price: 130 },
  ],
  notify: false,
},
{
  id: "10",
  title: "Rawayana Live",
  date: "2026-07-30",
  location: "Fort Lauderdale, FL",
  price: 95,
  fees: { service: 7, tax: 5 },
  deals: ["Summer special"],
  budget: [
    { type: "Standard", price: 95 },
    { type: "VIP", price: 150 },
  ],
  notify: true,
},
{
  id: "11",
  title: "Lindsey Stirling - Duality Untamed Tour",
  date: "2026-12-05",
  location: "Holmdel, NJ",
  price: 160,
  fees: { service: 12, tax: 9 },
  deals: ["Meet & greet"],
  budget: [
    { type: "Standard", price: 160 },
    { type: "VIP", price: 280 },
  ],
  notify: true,
},
{
  id: "12",
  title: "FKA Twigs – Body High Tour",
  date: "2026-03-18",
  location: "Brooklyn, NY",
  price: 140,
  fees: { service: 10, tax: 7 },
  deals: ["Limited edition poster"],
  budget: [
    { type: "Standard", price: 140 },
    { type: "VIP", price: 260 },
  ],
  notify: true,
},

{
  id: "13",
  title: "Sleep Token – Even in Arcadia Tour",
  date: "2026-09-22",
  location: "Philadelphia, PA",
  price: 110,
  fees: { service: 9, tax: 6 },
  deals: ["Early entry"],
  budget: [
    { type: "Standard", price: 110 },
    { type: "VIP", price: 190 },
  ],
  notify: false,
},

{
  id: "14",
  title: "SZA – SOS World Tour",
  date: "2026-08-14",
  location: "New York City, NY",
  price: 175,
  fees: { service: 14, tax: 9 },
  deals: ["Exclusive merch bundle"],
  budget: [
    { type: "Standard", price: 175 },
    { type: "VIP", price: 320 },
  ],
  notify: true,
},

{
  id: "15",
  title: "Bad Bunny – Most Wanted Tour",
  date: "2026-11-19",
  location: "Miami, FL",
  price: 550,
  fees: { service: 18, tax: 12 },
  deals: ["VIP backstage experience"],
  budget: [
    { type: "Standard", price: 220 },
    { type: "VIP", price: 420 },
  ],
  notify: true,
},
{
  id: "16",
  title: "The Weeknd – After Hours Til Dawn Tour",
  date: "2026-07-18",
  location: "New York City, NY",
  price: 210,
  fees: { service: 18, tax: 12 },
  deals: ["Early entry + exclusive poster"],
  budget: [
    { type: "Standard", price: 210 },
    { type: "VIP", price: 380 },
  ],
  notify: true,
},

{
  id: "17",
  title: "Djo – DECIDE Live",
  date: "2026-05-22",
  location: "Philadelphia, PA",
  price: 70,
  fees: { service: 7, tax: 5 },
  deals: ["Limited edition tour sticker"],
  budget: [
    { type: "Standard", price: 95 },
    { type: "VIP", price: 170 },
  ],
  notify: false,
},

{
  id: "18",
  title: "H.E.R. – Lights On Tour",
  date: "2026-09-03",
  location: "Newark, NJ",
  price: 160,
  fees: { service: 12, tax: 9 },
  deals: ["Free signed photo"],
  budget: [
    { type: "Standard", price: 160 },
    { type: "VIP", price: 290 },
  ],
  notify: true,
},

{
  id: "19",
  title: "Beyoncé – Renaissance Act II Tour",
  date: "2026-10-27",
  location: "Los Angeles, CA",
  price: 250,
  fees: { service: 20, tax: 14 },
  deals: ["VIP chrome club access"],
  budget: [
    { type: "Standard", price: 250 },
    { type: "VIP", price: 480 },
  ],
  notify: true,
},

];
